[gcp_service_account]
type = "service_account"
project_id = "recommend-app-467714"
private_key_id = "31f6c27afa402a3ad189a6d22790dac3c169d048"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGgDa1ZvRp32Bt
trB/tBFgvK11LAQNCUEpwhnVKXrcA51JmNn2jX9bxUidf55OX/n/tjsDFmf4LX4B
IVF2+kxx9YGjod3Z3DJfv/Byzw25NctcMX+QAlDKHD9ceRgRJHwYWz98MCBNtbLO
I+vOsL1MB9ilstQJ7DJHKfgZ2EaLfQu1IMMdFdsF9zbc/MUtKSuswwg93/XNygy6
e7JKXoEv39i6H7Ckvq5WU9Ynol5Rzh54EBSkuxfIh9ieRt6LdQkjS4p3xcQBKMT8
WXrF9muCZij4U2qXVbgm0O6sKQTn5LZFLkTjgZBTWDQvfHW6Hr/dLJ4o6iYfkm4a
+dt9Mxk/AgMBAAECggEACbYiIb6MvKqfZslmWd5vGeLWlayhR3CpeH006Fc5hI7E
tjdn39vNBv9gQxxdnAtZXtJakWxvimvSBgTMSIbhuz2TVHR0jIEXvH7WfmIfk20i
ADuyYv2fWD6zjDb8dMeVLq01g5eTLQTJCl7QMvI2AK9C69sTlqdbT7H/n7wTZNA+
PuMkMCH4+7VLCOijeih7dRO2ZSokCS3o9CROArpdFm6bv1BvuDYD57RjvAeVMx4s
wj+rujO9e+ZjgFFp9tgnDor+yxK4nWU/t34AhPH0nVLuxVsCo6mjOQgq4OJbyc8o
MF/MGKRUwS3DYsoP1lpbtOQrb2BbxjfpLyD1OzTOcQKBgQDw3neT8wdaRPIlEuQT
5P1kHcGrWbXs80kyG8rqtD4WlHfam5cXvc1wjsfJArQ0Xh8M8faC+662587S5Fdm
DPRRxHECEwGQMiiQwoqp4iAV8uy1ag/vZ5wVrrStb2qRZywmPFjtKyWwoYLe4mdi
X6mk+kFgamD2t8YNhRw8cu67ZwKBgQDS+GczvyKqxr8Rj3cdYKi8fuq62TWs7grW
QEUj9gN5ojeRRjNL9m0exRoHTxaSfSsgSZJsz2NuZlyc+G6Oe7nCClmdR7dRyxKj
d2N0Rwr8OLjrDl/MhK53RkIAKXTc7x7CsRaQBuOnQkeD8BxKi1TsiBGQ3pGpuwTR
7mYs7sxkaQKBgGW7kIXMf66AsEU4VVyRuvQuHT5iBZSurJudYXb/6blfu795N7ev
UrXXmEot+i6kEjlFePiZlJFsFs674q4Xipl+fryBiod8p+V8RVS7TRH4KEH3KgPT
nvkJcQZPqJMBIISFuIlzT9fqX3wD4+aIwP4NNM+kHpAVznCnZ+WgJXTBAoGBAK0i
C9esmO+bcPwhR3iFdZRTd6DlVqZXJ++SCOutHkb4uC9xc/F4By8ERAsRfY20SOsT
VaYUQB4+xOxQ+LHXmadDRS3MyAXI6L/b33NyRfKdPiwwvK+jh2X883ccjnothony
OHj0HmmJ/BSrvRvz4jrGo9vGu7WV9CuwQIvJYVVZAoGBAO+4q3HICSjGtl+2GTmA
9/3amQ+ABcXxtJo+eY9sM/opy+B9Q+EjShEhVSK+lWMP+slDXeSjri+d0Fg59iQT
lrXBHPtVcnq+A6iwRQoxlh2bUd3brym3GIgusx09FiG+S5r7emGagW6Klx3zy8FJ
158E6/9/h+1aHOO3NRvEYg5n
-----END PRIVATE KEY-----"""
client_email = "recommend-app-account@recommend-app-467714.iam.gserviceaccount.com"
client_id = "109642732667874590091"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/recommend-app-account%40recommend-app-467714.iam.gserviceaccount.com"

sheet_url = "https://docs.google.com/spreadsheets/d/10-gCQIm8MYGLjZir4M6nCuGjCMKgvJVZ-BblPLU3Fyo/edit"
